services:
    symfonian_id.core.manager_factory:
        class: Symfonian\Indonesia\CoreBundle\Toolkit\DoctrineManager\ManagerFactory

    symfonian_id.core.password_encoder:
        class: Symfonian\Indonesia\CoreBundle\Toolkit\Security\SymfonyIdPasswordEncoder